// <auto-generated />
namespace Ado6_1EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFix));
        
        string IMigrationMetadata.Id
        {
            get { return "202302091843304_AddFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
