//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado7_1EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssesment
    {
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string GroupName { get; set; }
        public string Faculty { get; set; }
        public Nullable<int> Assesment { get; set; }
    }
}
